<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block additionalProductList owl-carousel  <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block additionalProductList owl-carousel <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>

    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content products products-wrapper  block-<?php /* @escapeNotVerified */ echo $class?>" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item): ?>
        <?php $available = ''; ?>
        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
            <?php if (!$_item->getRequiredOptions()): ?>
                <?php $available = 'related-available'; ?>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($type == 'related' || $type == 'upsell'): ?>
            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item itemNewWrap" style="display: none;">' : '</div><div class="item product product-item itemNewWrap" style="display: none;">' ?>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item itemNewWrap">' : '</div><div class="item product product-item itemNewWrap">' ?>
        <?php endif; ?>
        <div class="product-item-info item-absolute <?php /* @escapeNotVerified */ echo $available; ?>">
            <div class="select-wrap-static">
                <div class="select-wrap">
                    <select data-placeholder="Choose metal" class="orange-sel">
                        <option></option>
                        <option value="Bronze">Bronze</option>
                        <option value="Aluminium">Aluminium</option>
                        <option value="Gold">Gold</option>
                    </select>
                </div>
                <?php //if ($showDescription):?>
                <a class="show-item-details"></a>
                <?php //endif; ?>
                <a href="#" class="toggle-360"></a>
            </div>

            <div class="item-view-wrap-static">
                <?php //if ($showDescription):?>
                    <div class="item-details-popup">
                        <ul>
                            <li><strong>Shape:</strong> Round</li>
                            <li><strong>Material:</strong> Stainless steel</li>
                            <li><strong>Case Back:</strong> Screw-down case back</li>
                            <li><strong>Shape:</strong> Round</li>
                            <li><strong>Material:</strong> Stainless steel</li>
                        </ul>
                        <?php ///* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>
                <?php //endif; ?>
                <div class="item-view-wrap">
                    <div class="round-view">
                        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                        </a>
                    </div>
                    <div class="additional-details-wrap">
                        <div class="bottom-controls">
                            <?php //if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist like-this" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                </a>
                            <?php //endif; ?>
                            <a href="#" class="quick-view"></a>
                            <a href="#" class="share-this"></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item-description">
                <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                    <?php echo $block->escapeHtml($_item->getName()) ?>
                </a>
            </div>
            <div class="item-price">
                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                <?php if ($templateType): ?>
                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                <?php endif; ?>
            </div>
            <div class="buttons-wrap">
                <?php if ($_item->isSaleable()): ?>
                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                        <button class="action tocart primary button-gold item-get-this" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                        </button>
                    <?php else: ?>
                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                        ?>
                        <button class="action tocart primary button-gold item-get-this"
                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                        </button>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if ($_item->getIsSalable()): ?>
                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                    <?php else: ?>
                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
        <?php endforeach ?>
    </div>
</div>
<?php endif;?>
