<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php if($product->getAttributeText('online_product') == 'Yes'):?>
    <?php $buttonTitle = __('Add to Cart'); ?>
    <?php if ($product->isSaleable()): ?>
        <button type="submit"
                title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                class="action primary tocart addToCart button-gold color-dark big"
                id="product-addtocart-button">
            <?php /* @escapeNotVerified */ echo $buttonTitle ?>
        </button>
        <?php echo $block->getChildHtml('', true) ?>
    <?php endif; ?>
    <?php if ($block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
    <?php else : ?>
        <script>
            require([
                'jquery',
                'mage/mage',
                'Magento_Catalog/product/view/validation',
                'Magento_Catalog/js/catalog-add-to-cart'
            ], function ($) {
                'use strict';

                $('#product_addtocart_form').mage('validation', {
                    radioCheckboxClosest: '.nested',
                    submitHandler: function (form) {
                        var widget = $(form).catalogAddToCart({
                            bindSubmit: false
                        });

                        widget.catalogAddToCart('submitForm', $(form));

                        return false;
                    }
                });
            });
        </script>
    <?php endif; ?>
    <?php else: ?>
    <button class="addToCart button-gold color-dark big"><?php echo __('Find Nearby Store');?></button>
<?php endif;?>





