<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <button
        class="action towishlist addToWishList button-gold color-dark-reverse big"
        data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
        data-action="add-to-wishlist "><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></button>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions($product))?>
        }
    }
</script>