<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$product = $block->getSaleableItem();
$productId = $product->getId();

/** @var \Magento\Catalog\Pricing\Price\RegularPrice $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Catalog\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

$_web_helper = $this->helper('Dtrof\Catalog\Helper\Data');
$website_id = $_web_helper->getCurrentWebsite();
?>

<?php if($product->getAttributeText('online_product') == 'Yes' && ($website_id == 7 || $website_id == 6)):?>
    <?php if ($block->hasSpecialPrice()): ?>
        <span class="old-price oldPrice">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
//                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
        <span class="special-price mainPrice">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
//                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>

    <?php else: ?>
        <span class="special-price mainPrice">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
       </span>
    <?php endif; ?>

    <!--    --><?php //if ($block->showMinimalPrice()): ?>
    <!--        --><?php //if ($block->getUseLinkForAsLowAs()):?>
    <!--            <a href="--><?php ///* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?><!--" class="minimal-price-link">-->
    <!--                --><?php ///* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
    <!--            </a>-->
    <!--        --><?php //else:?>
    <!--            <span class="minimal-price-link">-->
    <!--                --><?php ///* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
    <!--            </span>-->
    <!--        --><?php //endif?>
    <!--    --><?php //endif; ?>
<?php endif; ?>