<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_banner= $block->getCurrentCategory()->getBrandBanner()): ?>
<div class="jewelleryBanner">
    <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_banner, 'brand_banner') ?>

    <!--<div class="video-wrap">
        <div id="player"></div>
        <div class="video-buttons">
            <span class="video-action full-screen">Full screen</span>
            <span class="video-action mute">Mute</span>
        </div>
    </div>-->
    <div class="player-wrap">
        <div id="player"></div>
    </div>
</div>

    <script>
        var youtubeLink = document.querySelector('.jewelleryBanner > p').innerText,
            youtubeCode = youtubeLink.substring( youtubeLink.indexOf('youtu.be/') + 9 );

        var tag = document.createElement('script'), notPlayed = true;
        tag.src = "https://www.youtube.com/iframe_api";

        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        var player, allowScroll = true;

        function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
                height: '390',
                width: '640',
                videoId: youtubeCode,
                events: {
                    'onReady': onPlayerReady,
                    'onStateChange': onPlayerStateChange
                }
            });
        }

        function onPlayerStateChange(){
            notPlayed = (player.getPlayerState() == 1) ? false : true;
        }
        function onPlayerReady() {
            var elementBox = document.querySelector('#player');
            document.querySelector('.player-wrap').addEventListener('click', function(event){
                allowScroll = false;
                player.pauseVideo();
                var cls = event.target.className;
                event.target.className = cls+" clicked";
            });
            function check_if_in_view(){
                var elementBoxTop = elementBox.getBoundingClientRect().top + window.pageYOffset,
                    elementBoxBottom = elementBox.getBoundingClientRect().bottom + window.pageYOffset,
                    wh = window.innerHeight + window.pageYOffset;

                if ( wh > elementBoxTop && window.pageYOffset < elementBoxBottom && allowScroll) {
                    if(notPlayed){
                        player.playVideo();
                        notPlayed = false;
                    }
                }else if(!notPlayed && allowScroll){
                    player.pauseVideo();
                    notPlayed = true;
                }
            }

            check_if_in_view();
            window.addEventListener('scroll', check_if_in_view);
        }
    </script>


<!--<script>
    var youtubeLink = document.querySelector('.jewelleryBanner > p').innerText;
    var youtubeCode = youtubeLink.substring( youtubeLink.indexOf('youtu.be/') + 9 );
    console.log('youtubeCode - '+youtubeCode);

    if( youtubeLink.indexOf('youtu.be/') > 0 ){
        if (!window['YT']) {
            var YT = {loading: 0,loaded: 0};
        }
        if (!window['YTConfig']) {
            var YTConfig = {'host': 'http://www.youtube.com'};
        }
        if (!YT.loading) {
            YT.loading = 1;
            (function(){
                var l = [];
                YT.ready = function(f) {
                    if (YT.loaded) {f();
                    } else {
                        l.push(f);
                    }
                };
                window.onYTReady = function() {
                    YT.loaded = 1;
                    for (var i = 0; i < l.length; i++) {
                        try {l[i]();} catch (e) {}
                    }
                };
                YT.setConfig = function(c) {
                    for (var k in c) {
                        if (c.hasOwnProperty(k)) {YTConfig[k] = c[k];}
                    }
                };
                var a = document.createElement('script');
                a.type = 'text/javascript';
                a.id = 'www-widgetapi-script';
                a.src = 'https:' + '//s.ytimg.com/yts/jsbin/www-widgetapi-vfllcOhKV/www-widgetapi.js';
                a.async = true;
                var b = document.getElementsByTagName('script')[0];
                b.parentNode.insertBefore(a, b);
            })();
        }

        function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
                height: '390',
                width: '640',
                videoId: youtubeCode,
                playerVars: {
                    modestbranding: 1,
                    controls: 0,
                    disablekb: 0,
                    rel:0,
                    //showinfo: 0,
                    loop: 0,
                    playlist: youtubeCode
                },
                events: {'onReady': onPlayerReady}
            });
        }
        function onPlayerReady(event) {
            document.querySelector('.jewelleryBanner').style.display='block';
            var playerEvent = event,
                videoWrapper = document.querySelector('.video-wrap');


            videoWrapper.addEventListener('mouseover', function(){
                playerEvent.target.playVideo();
            });
            videoWrapper.addEventListener('mouseout', function(){
                playerEvent.target.pauseVideo();
            });

            var muteButton = document.querySelector('.video-action.mute');
            muteButton.addEventListener('click', function(event){
                var classElement = event.target.className;
                if( classElement.indexOf('clicked') > -1 ){
                    event.target.className='video-action mute';
                    player.unMute();

                }else{
                    event.target.className +=' clicked';
                    player.mute();
                }
            });
        }

        var fullScreenButton = document.querySelector('.video-action.full-screen');
        fullScreenButton.addEventListener('click', function(){
            var videoWrapper = document.querySelector('.video-wrap');
            if( videoWrapper.className.indexOf('full-screen') > -1 ){
                videoWrapper.className = 'video-wrap';
                event.target.className='video-action full-screen';
                document.querySelector('body').style.overflow='initial';
            }else{
                videoWrapper.className = 'video-wrap full-screen';
                event.target.className='video-action full-screen clicked';
                document.querySelector('body').style.overflow='hidden';
            }
        });
    }

    setTimeout(function(){
        console.log('Timo out');
        var css = 'a.ytp-watermark.yt-uix-sessionlink {display: none;}',
            style = document.createElement('style');
        style.type = 'text/css';
        if (style.styleSheet){
            style.styleSheet.cssText = css;
        } else {
            style.appendChild(document.createTextNode(css));
        }
        document.querySelector('.video-wrap').appendChild(style);
    }, 10000);

</script>-->

<?php endif; ?>
