<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Variations');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Variations');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('YOU MAY ALSO LIKE');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('YOU MAY ALSO LIKE');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_web_helper = $this->helper('Dtrof\Catalog\Helper\Data');
$website_id = $_web_helper->getCurrentWebsite();
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block additionalProductList <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block additionalProductList <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>

    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content products products-wrapper owl-carousel  block-<?php /* @escapeNotVerified */ echo $class?>" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item): ?>
            <?php
            $block->setProduct($_item);
            $productType = $_item->getTypeId();
            $attributes = array();
            if($productType != 'watches'){
                $attribute = $block->getAdditionalData(array('metal_purity','metal_color','metal_type','main_stone_type','stone'));
                $metal_purity = (!empty($attribute['metal_purity']['value']))?$attribute['metal_purity']['value'].' ':'';
                $metal_color = (!empty($attribute['metal_color']['value']))?$attribute['metal_color']['value'].' ':'';
                $metal_type = (!empty($attribute['metal_type']['value']))?$attribute['metal_type']['value'].' ':'';
                $main_stone_type = (!empty($attribute['main_stone_type']['value']))?$attribute['main_stone_type']['value'].' ':'';
                $stone = (!empty($attribute['stone']['value']))?', '.$attribute['stone']['value']:'';
                if(!empty($attribute)){
                    $attributes = array(
                        $metal_purity.''.$metal_color.''.$metal_type,
                        $main_stone_type.''.$stone
                    );
                }

            }else{
                $attribute = $block->getAdditionalData(array('watches_metal_purity',
                    'watches_metal_color',
                    'watches_metal_type',
                    'watches_stone_type'));

                $metal_purity = (!empty($attribute['watches_metal_purity']['value']))?$attribute['watches_metal_purity']['value'].' ':'';
                $metal_color = (!empty($attribute['watches_metal_color']['value']))?$attribute['watches_metal_color']['value'].' ':'';
                $metal_type = (!empty($attribute['watches_metal_type']['value']))?$attribute['watches_metal_type']['value'].' ':'';
                $stone_type = (!empty($attribute['watches_stone_type']['value']))?$attribute['watches_stone_type']['value'].' ':'';
                if(!empty($attribute)){
                    $attributes = array(
                        $metal_purity.''.$metal_color.''.$metal_type,
                        $stone_type
                    );
                }

            }


            $productImage = $block->getImage($_item, $image);
            $imageData = $productImage->getData();
            $image360 = $block->getRenderedHtml($_item);
            ?>
        <?php $available = ''; ?>
        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
            <?php if (!$_item->getRequiredOptions()): ?>
                <?php $available = 'related-available'; ?>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($type == 'related' || $type == 'upsell'): ?>
            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item itemNewWrap" style="display: none;">' : '</div><div class="item product product-item itemNewWrap" style="display: none;">' ?>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item itemNewWrap">' : '</div><div class="item product product-item itemNewWrap">' ?>
        <?php endif; ?>
        <div class="product-item-info item-absolute <?php /* @escapeNotVerified */ echo $available; ?>">
            <div class="select-wrap-static">
                <div class="select-wrap">
                    <?php if(!empty($attributes)) : ?>
                        <a class="show-item-details"></a>
                    <?php endif; ?>
                </div>
                <?php if($image360 != ''):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="toggle-360"></a>
                <?php endif;?>

            </div>

            <div class="item-view-wrap-static">
                <?php if(!empty($attributes)) : ?>
                    <div class="item-details-popup">
                        <ul>
                            <?php foreach($attributes  as $key=>$_data) : ?>
                                <li>
                                    <span><?php echo $_data;?><?php echo ($key == 0 && !empty($attributes[1]))?', ':'';?></span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
                <div class="item-details-share">
                    <div class="item-details-socialBlock">
                        <a href="https://www.facebook.com/sharer.php?u=<?php echo $block->getProductUrl($_item);?>" class="fb icon-social"></a>
                        <a href="https://twitter.com/intent/tweet?url=<?php echo $block->getProductUrl($_item);?>&text=<?php echo $block->escapeHtml($_item->getName());?>" class="tw icon-social"></a>
                        <a href="https://plus.google.com/share?url=<?php echo $block->getProductUrl($_item);?>" target="_blank" class="gp icon-social"></a>
                        <a href="whatsapp://send?text=<?php echo $block->getProductUrl($_item);?>"  target="_blank" class="wt icon-social"></a>
                        <?php if($imageData['image_url'] != '') : ?>
                            <a href="https://pinterest.com/pin/create/bookmarklet/?media=<?php echo $imageData['image_url']; ?>&url=<?php echo $block->getProductUrl($_item);?>&description=<?php echo $block->escapeHtml($_item->getName());?>"
                               target="_blank" class="pt icon-social"></a>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="item-view-wrap">
                    <div class="round-view">
                        <?php if($image360 != ''){
                            echo $image360;
                        }else{ ?>
                            <a href="<?php echo $block->getProductUrl($_item);?>" title="">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                        <?php } ?>
                    </div>
                    <div class="additional-details-wrap">
                        <div class="bottom-controls">
                            <?php //if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist like-this" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                </a>
                            <?php //endif; ?>
                            <a href="/ajax/quickview/product/?id=<?=$_item->getId()?>"
                               data-fancybox-type="iframe"
                               class="quick-view fancybox-ajax"></a>
                            <a href="#" class="share-this"></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item-description">
                <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                    <?php echo $block->escapeHtml($_item->getName()) ?>
                </a>
            </div>
            <div class="item-price">
                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                <?php if ($templateType): ?>
                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                <?php endif; ?>
            </div>
            <div class="buttons-wrap">
                <?php if ($_item->isSaleable()): ?>
                <?php if ($productType == 'watches'): ?>
                        <a href="/ajax/popup/item/?id=<?=$_item->getId()?>" class="button-gold color-dark item-get-this productItemPopup"><?php echo $block->escapeHtml(__('Request for quote')); ?></a>
                    <?php else:?>

                        <?php if($_item->getAttributeText('online_product') == 'Yes' && ($website_id == 7 || $website_id == 6)):?>
                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                <button class="action tocart primary button-gold item-get-this" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php else: ?>
                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                ?>
                                <button class="action tocart primary button-gold item-get-this"
                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php endif; ?>
                        <?php else: ?>
                            <div class="buttons-wrap">
                                <a href="/ajax/popup/item/?id=<?=$_item->getId()?>"
                                   class="button-gold color-dark item-get-this productItemPopup">
                                    <?php echo $block->escapeHtml(__('get this item')); ?>
                                </a>
                            </div>
                        <?php endif; ?>

                <?php endif;?>


                <?php else: ?>
                    <?php if ($_item->getIsSalable()): ?>
                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                    <?php else: ?>
                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                    <?php endif; ?>

                <?php endif; ?>
            </div>
        </div>
        <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
        <?php endforeach ?>
    </div>
</div>
<?php endif;?>
