<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

?>
<?php if ($block->getPagerHtml()): ?>
    <div class="toolbar toolbar-products" >
        <?php echo $block->getPagerHtml() ?>
    </div>
<?php endif ?>
