<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!--<a href="/ajax/popup/callback/?id=--><?php //echo $_product->getId();?><!--"-->
<!--   data-href="/ajax/popup/callback/?id=--><?php //echo $_product->getId();?><!--"-->
<!--   class="functionalPopup requestToCallback">--><?php //echo __('Request to callback');?><!--</a>-->
<!--<a href="/ajax/popup/mail/?id=--><?php //echo $_product->getId();?><!--"-->
<!--   class="functionalPopup requestToEmailback">--><?php //echo __('Receive a quote to email');?><!--</a>-->
<button class="addToCart button-gold color-dark big nearbyStore" data-href="/stores"><?php echo __('Find Nearby Store');?></button>

<!--<button class="addToCart button-gold color-dark big">--><?php //echo __('Get this item');?><!--</button>-->