<div class="topInfo row">
    <div class="productSku col-md-6">
        <p>SKU: <span>914553</span></p>
    </div>
    <div class="socialLinks col-md-6">
        <a href="#" class="facebook"></a>
        <a href="#" class="instagram"></a>
        <a href="#" class="twitter"></a>
        <a href="#" class="youtube"></a>
    </div>
</div>
<div class="prodDescription">
    <div class="select-wrap selectOptions">
        <label>Select options:</label>
        <select>
            <option value="2">10K yellow gold</option>
            <option value="3">20K red gold</option>
            <option value="4">30K dark gold</option>
        </select>
    </div>
    <div class="select-wrap ringSize">
        <label>Ring size:</label>
        <div class="toolTip">?
            <span>some tooltip information, some tooltip information.</span>
        </div>
        <select>
            <option value="2">4,5</option>
            <option value="3">5,5</option>
            <option value="4">6,5</option>
        </select>
    </div>
    <div class="priceWrap">
        <span class="oldPrice">$1,700</span>
        <span class="mainPrice">$12,099</span>
    </div>
    <div class="prodButtons">
        <button class="addToCart button-gold color-dark big">Get this item</button>
        <button class="addToWishList button-gold color-dark-reverse big">Add to wishlist</button>
    </div>

    <a href="#" class="functionalPopup">Engraving is free as well</a>

    <p>Black PVD stainless steel case with a brown leather strap. Fixed
        black PVD bezel. Petrol blue dial with white hands and index and
        Arabic numeral hour markers. The Alpina logo marks the 12 o'clock
        position. Minute markers around the outer rim. Dial Type: Analog.
        Luminescent hands. Date display at the 6 o'clock position. Chrono-
        graph - three sub-dials displaying: 60 second, 30 minute and 1/10th
        of a second.</p>
</div>