<div class="topInfo row">
    <div class="productSku col-md-6">
        <p>SKU: <span>914553</span></p>
    </div>
    <div class="socialLinks col-md-6">
        <a href="#" class="facebook"></a>
        <a href="#" class="instagram"></a>
        <a href="#" class="twitter"></a>
        <a href="#" class="youtube"></a>
    </div>
</div>
<div class="prodDescription">
    <h4>WATCH SPECIFICATIONS:</h4>
    <p>Black PVD stainless steel case with a brown leather strap. Fixed
        black PVD bezel. Petrol blue dial with white hands and index and
        Arabic numeral hour markers. The Alpina logo marks the 12 o'clock
        position. Minute markers around the outer rim. Dial Type: Analog.
        Luminescent hands. Date display at the 6 o'clock position. Chrono-
        graph - three sub-dials displaying: 60 second, 30 minute and 1/10th
        of a second.</p>
</div>
<div class="prodButtons">
    <button class="addToCart button-gold color-dark big">Get this item</button>
    <button class="addToWishList button-gold color-dark-reverse big">Add to wishlist</button>
</div>