<?php
$root_option_id = 0;
$entity_id = (int)$this->getRequest()->getParam('id');
$categories = $block->getChild();
$attributes = $block->getRootAttribute($entity_id);
$url =  $block->getCategoryUrl();
$urlParams =  $block->getParamsUrl();
if(!empty($attribute)){
    if($this->getRequest()->getParam($attributes['attribute_code'])) {
        $root_option_id = $this->getRequest()->getParam($attributes['attribute_code']);
    }
}
?>
<?php if(!empty($categories)):?>
    <div class="giftsTopLeftFilter">
        <h4><?php echo __('GIFT FILTER');?></h4>
        <?php if(!empty($categories)):?>
            <div class="selectFilter">
                <p class="filterTitle"><?php echo __('For Whom');?></p>
                <div class="select-wrap">
                    <div class="site-selected"><span><?=$block->getCategoryName();?></span></div>
                    <ul class="sites-options">
                        <?php foreach($categories as $item):?>
                            <?php if($entity_id !=  $item['entity_id']):?>
                                <li>
                                    <a href="/<?php echo $item['request_path']?><?=$urlParams?>" class="gift-link"><?php echo $item['name']?></a>
                                </li>
                            <?php endif;?>
                        <?php endforeach;?>
                    </ul>
                </div>
            </div>
        <?php endif;?>
        <?php
        if(!empty($attributes)){
            include ($block->getTemplateFile('Dtrof_Gifts::gift_top_filter_tree.phtml'));
        }else{
            include ($block->getTemplateFile('Dtrof_Gifts::gift_top_filter_without_tree.phtml'));
        }
        ?>
    </div>
<?php endif;?>

