<?php
$request = $this->getRequest()->getParams();
$attributes = $block->getAttribute($request['configuration_id'],$request['attribute_id'],$request['parent_id'])?>
<div class="filterCircle ">
    <?php if(!empty($attributes)):?>
        <p class="filterTitle"><?=$attributes['frontend_label'];?></p>
        <div class="table-wrapper">
            <?php foreach($attributes['options'] as $options):?>
                <label class="filter-icon-block option-label-image link_<?=$attributes['configuration_id']?>_<?=$attributes['next_id']?>_<?=$options['link_id'];?>"
                    <?php if($attributes['last'] == 1) : ?>
                        onclick="window.oyiGifts.showSubmitButton();"
                    <?php else : ?>
                        onclick="window.oyiGifts.step(<?=$attributes['configuration_id']?>,<?=$attributes['next_id']?>,<?=$options['link_id'];?>);"
                    <?php endif; ?>
                        >
                    <span class="filter-icon-img" style="background-image: url('<?=$options['image']?>')"></span>
                    <input type="radio" name="<?=$attributes['attribute_code'];?>" value="<?=$options['option_id'];?>">
                    <span class="filter-icon-title"><?=$options['value']?></span>
                </label>
            <?php endforeach;?>
        </div>
    <?php endif;?>
</div>
<div id="content_<?=$attributes['next_code']?>"  class="filterItemBlock"></div>