<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<h4>
    <a <?php /* @escapeNotVerified */ echo $block->getLinkAttributes() ?>>
        <?php echo $block->escapeHtml($block->getLabel()) ?>
    </a>
</h4>
<!--<a <?php /*/* @escapeNotVerified */ //echo $block->getLinkAttributes() */?>><?php /*echo __('start shopping'); */?></a>-->