<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<script>
    require([
        "jquery",
        "mage/adminhtml/form",
        "Dtrof_Gifts/js/admin"
    ], function(jQuery) {
        console.log('init');
    })
</script>