<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Dtrof\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

?>
<?php if ($block->isEnabledViewSwitcher()): ?>
    <div class="col-lg-6 col-xs-12 items-view-controls">
        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/online.phtml')) ?>
        <div class="viewChangeWrapper">
            <?php $_modes = $block->getModes(); ?>
            <?php if ($_modes && count($_modes) > 1): ?>
                <label><?php /* @escapeNotVerified */ echo __('View as') ?></label>
                <?php foreach ($block->getModes() as $_code => $_label): ?>
                    <?php if ($block->isModeActive($_code)): ?>
                        <strong title="<?php /* @escapeNotVerified */ echo $_label ?>"
                                class="modes-mode active mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                                data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                        </strong>
                    <?php else: ?>
                        <a class="modes-mode mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?> form-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>-view"
                           title="<?php /* @escapeNotVerified */ echo $_label ?>"
                           href="#"
                           data-role="mode-switcher"
                           data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                           id="mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                           aria-labelledby="modes-label mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                        <!-- <span>--><?php ///* @escapeNotVerified */ echo $_label ?><!----><?php ///* @escapeNotVerified */ echo strtolower($_code); ?><!--</span>-->
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
