<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount buttons" id="block-discount">
    <form id="discount-coupon-form"
          action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/couponPost') ?>"
          method="post"
          data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                           "removeCouponSelector": "#remove-coupon",
                                           "applyButton": "button.action.apply",
                                           "cancelButton": "button.action.cancel"}}'>
        <div class="fieldset coupon<?php strlen($block->getCouponCode()) ? ' applied' : ''?>">
            <input type="hidden" name="remove" id="remove-coupon" value="0" />
            <label for="coupon_code" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Gift voucher code') ?></span>
            </label>
            <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $block->escapeHtml($block->getCouponCode()) ?>" />

            <?php if (!strlen($block->getCouponCode())): ?>
            <button class="action apply primary button-gold color-dark" type="button" value="<?php /* @escapeNotVerified */ echo __('Enter') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Enter') ?></span>
            </button>
            <?php else: ?>
            <button  type="button" class="action cancel primary button-gold color-dark" value="<?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?></span>
            </button>
            <?php endif; ?>
        </div>

    </form>
</div>
