<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: cart().summary_count --><!-- /ko --></span>
        </span>
    </a>
<!--    --><?php //if ($block->getIsNeedToDisplaySideBar()): ?>
<!--        <div class="block block-minicart empty"-->
<!--             data-role="dropdownDialog"-->
<!--             data-mage-init='{"dropdownDialog":{-->
<!--                "appendTo":"[data-block=minicart]",-->
<!--                "triggerTarget":".showcart",-->
<!--                "timeout": "2000",-->
<!--                "closeOnMouseLeave": false,-->
<!--                "closeOnEscape": true,-->
<!--                "triggerClass":"active",-->
<!--                "parentClass":"active",-->
<!--                "buttons":[]}}'>-->
<!--            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">-->
<!--                <!-- ko template: getTemplate() --><!-- /ko -->
<!--            </div>-->
<!--        </div>-->
<!--    --><?php //endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('img/loader.gif'); ?>"
        }
    }
    </script>
</div>
<div class="wrap-tg-btn">
    <div class="tg-button" id="nav-toggle">
        <span class="sp-1"></span>
        <span class="sp-2"></span>
        <span class="sp-3"></span>
    </div>
</div>


