<section class="contactUsPopUp" id="contactUsPopUp">
    <h1>Contact us</h1>
    <div class="contactUs_container">
        <div class="contactUs_left contactUs_inner">
            <h4>CUSTOMER SERVICE DEPARTMENT</h4>
            <ul>
                <li><strong>Telephone:</strong> 800-DAMAS (32627)</li>
                <li><strong>Fax:</strong> +9714 445 9553</li>
                <li><strong>E-mail:</strong> Customer@damasjewellery.com</li>
            </ul>

            <h4>HUMAN RESOURCE DEPARTMENT</h4>
            <ul>
                <li><strong>Telephone:</strong> +9714 445 9000</li>
                <li><strong>Fax:</strong> +9714 445 9505</li>
                <li><strong>E-mail:</strong> Hr@damasjewellery.com</li>
            </ul>

            <p><a href="#">Live chat with us</a></p>

        </div>
        <div class="contactUs_right contactUs_inner">
            <h4>SEND A MESSAGE</h4>
            <form action="#">
                <div class="input-group">
                    <label for="contuctUs_name">Enter your name*</label>
                    <input id="contuctUs_name" type="text" placeholder="First name">
                </div>
                <div class="input-group">
                    <label for="contuctUs_name">Enter your e-mail*</label>
                    <input id="contuctUs_name" type="text" placeholder="E-mail">
                </div>
                <div class="input-group">
                    <label for="contuctUs_name">Enter your phone</label>
                    <input id="contuctUs_name" type="text" placeholder="Phone">
                </div>
                <div class="input-group">
                    <label for="contuctUs_name">Enter your message*</label>
                    <textarea id="contuctUs_name" type="text" placeholder="Message"></textarea>
                </div>
                <div class="input-group buttons-block">
                    <button type="submit" title="Create an Account" class="button-gold color-dark">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>