<div class="giftsPage giftIdeas">
    <h1>GIFT IDEAS</h1>
    <div class="container">
        <div class="gift-section-wrap">
            <div class="link-items giftsAdvs">
                <div class="item col-md-4 effect-sadie">
                    <div class="caption">
                        <img src="http://loc.damas/pub/media/wysiwyg/for-her.jpg" alt="" />
                        <h4>For Her</h4>
                        <a href="http://loc.damas/gifts/gifts-for-her.html?___store=en">start shopping</a>
                    </div>
                </div>
                <div class="item col-md-4 effect-sadie">
                    <div class="caption">
                        <img src="http://loc.damas/pub/media/wysiwyg/for-him.jpg" alt="" />
                        <h4>For Him</h4>
                        <a href="http://loc.damas/gifts/gifts-for-him.html?___store=en">start shopping</a>
                    </div>
                </div>
                <div class="item col-md-4 effect-sadie">
                    <div class="caption">
                        <img src="http://loc.damas/pub/media/wysiwyg/for-kids.jpg" alt="" />
                        <h4>Kids</h4>
                        <a href="http://loc.damas/gifts/gift-for-kids.html?___store=en">start shopping</a>
                    </div>
                </div>
            </div>
        </div>
        <form class="filterSections">
            <div class="filterRelationship filterCircle filterItemBlock">
                <p class="filterTitle">Relationship</p>
                <label class="icon-sister"><input type="radio" name="relationship"><span>sister</span></label>
                <label class="icon-wife"><input type="radio" name="relationship"><span>wife</span></label>
                <label class="icon-mother"><input type="radio" name="relationship"><span>mother</span></label>
                <label class="icon-friend"><input type="radio" name="relationship"><span>friend</span></label>
                <label class="icon-colleague"><input type="radio" name="relationship"><span>colleague</span></label>
                <label class="icon-grandma"><input type="radio" name="relationship"><span>grandma</span></label>
                <label class="icon-daughter"><input type="radio" name="relationship"><span>daughter</span></label>
                <label class="icon-other"><input type="radio" name="relationship"><span>other</span></label>
            </div>
            <div class="filterOccasions filterCircle filterItemBlock">
                <p class="filterTitle">Occasions</p>
                <label class="icon-birthday"><input type="radio" name="occasions"><span>birthday</span></label>
                <label class="icon-graduation"><input type="radio" name="occasions"><span>graduation</span></label>
                <label class="icon-anniversary"><input type="radio" name="occasions"><span>anniversary</span></label>
                <label class="icon-ramadan"><input type="radio" name="occasions"><span>ramadan</span></label>
                <label class="icon-christmas"><input type="radio" name="occasions"><span>christmas</span></label>
                <label class="icon-diwali"><input type="radio" name="occasions"><span>diwali</span></label>
                <label class="icon-wedding"><input type="radio" name="occasions"><span>wedding</span></label>
                <label class="icon-valentine"><input type="radio" name="occasions"><span>valentine</span></label>
                <label class="icon-other2"><input type="radio" name="occasions"><span>other</span></label>
            </div>
            <div class="filterStyles filterRectangle filterItemBlock">
                <p class="filterTitle">Styles</p>
                <label class="filterRectItem"><input type="radio" name="styles">classic</label>
                <label class="filterRectItem"><input type="radio" name="styles">retro</label>
                <label class="filterRectItem"><input type="radio" name="styles">unique</label>
                <label class="filterRectItem"><input type="radio" name="styles">modern</label>
                <label class="filterRectItem"><input type="radio" name="styles">antique</label>
                <label class="filterRectItem"><input type="radio" name="styles">art deco</label>
                <label class="filterRectItem"><input type="radio" name="styles">cocktail</label>
                <label class="filterRectItem"><input type="radio" name="styles">vantage</label>
                <label class="filterRectItem"><input type="radio" name="styles">georgian</label>
                <label class="filterRectItem"><input type="radio" name="styles">other</label>
            </div>
            <div class="filterButtonsBlock">
                <button class="button-gold color-dark">Search gifts</button>
            </div>
        </form>
    </div>
</div>