<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
select.phtml
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="select-wrap selectOptions field<?php /* @escapeNotVerified */ echo $class; ?>">
    <label for="select_<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <?php echo  $block->escapeHtml($_option->getTitle()) ?>
    </label>

    <?php echo $block->getValuesHtml() ?>
    <?php if ($_option->getIsRequire()): ?>
        <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
            <span id="options-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></span>
        <?php endif; ?>
    <?php endif;?>

</div>
